repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: ['--maxkb=10240']
  - id: check-yaml
  - id: debug-statements
  - id: check-merge-conflict
  - id: mixed-line-ending
    args: ['--fix=lf']

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    args: [--line-length=120]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.11
  hooks:
  - id: ruff
    args: ['--line-length=120', '--fix']
